### ISSUE TITLE
Single posts without sidebar do not take up full width

### ISSUE THREAD

**Issue by KevinEady** [terrylinooo/githuber#1]
Hi @terrylinooo ,

Thanks again for helping with the Githuber MD plugin + gist embedding. 

My posts do not have a sidebar, and unfortunately this means there's still a lot of whitespace on the right side of my single posts.

I think it's because the column dimension is not dynamic based off of the sidebar's active status:
 https://github.com/terrylinooo/githuber/blob/5923c09bb639b80561283c5355688fc8a5b69f6d/single.php#L44

I made some changes like this:

```php
<?php if (is_active_sidebar( 'sidebar-1' ) || is_active_sidebar( 'sidebar-3' ) ) : ?>
	<main id="main-container" class="col-lg-8 col-md-8 col-sm-12" role="main">
<?php else: ?>
	<main id="main-container" class="col-sm-12" role="main">
<?php endif; ?>
```

and only including the aside container if the sidebar is active.

```php
<?php if (is_active_sidebar( 'sidebar-1' ) || is_active_sidebar( 'sidebar-3' ) ) : ?>
	<aside id="aside-container" class="col-lg-4 col-md-4 col-sm-12" role="complementary">
		<?php get_sidebar(); ?>
	</aside>
<?php endif; ?>
```

Does this make sense? It's my first time dabbling in WordPress. Should I create a fork + PR request?

**Comment by terrylinooo** [comment]
@KevinEady Thanks. It is good idea. Welcome to send a pull request!

Githuber theme has changed its name because of possible trademark issue. You can check out the new address here:
https://github.com/terrylinooo/mynote

And also, you can find "Mynote" theme on WordPress theme directory now.
