### ISSUE TITLE
Comments URL fix.

### ISSUE THREAD

**Issue by KevinJDurant** [terrylinooo/githuber#1]
**Describe the bug**
Hi, I think you forgot to add `' . esc_url( get_the_permalink() ) . '` to the comments balloon. Figured I wouldn't open a PR as I don't have PHP Sniffer installed. Awesome theme!

https://github.com/terrylinooo/githuber/blob/91d19664e16fb705024987586788e2331095f65f/themes/githuber/functions.php#L964

https://github.com/terrylinooo/githuber/blob/91d19664e16fb705024987586788e2331095f65f/themes/githuber/functions.php#L946

**To Reproduce**
/

**Expected behavior**
/

**Screenshots**
/

**Desktop (please complete the following information):**
/

**Smartphone (please complete the following information):**
/

**Additional context**
/

**Comment by terrylinooo** [comment]
Ok! thank you! I will fix it soon.
