### ISSUE TITLE
Uncatergorized 500 error

### ISSUE THREAD

**Issue by cbebek** [terrylinooo/githuber#2]
Hi there,
You theme gives me a 500 error when I click uncategorized:

https://chrisbebek.com/blog/?cat=1

I've tried several other themes from the wordpress repo with no issues, any idea?

Wordpress installed on /blog subfolder
Centos 7 enforcing

**Comment by terrylinooo** [comment]
Hello, thank you very much for reporting this issue.
It is caused by PHP version, the empty() only support varible before PHP 5.5
I have fixed it and update the category.php
You can download 1.08 and try again.

**Comment by cbebek** [comment]
Ah because I had no posts yet?

**Comment by terrylinooo** [comment]
It is because of PHP version. I should note that. Thank you again.
