### ISSUE TITLE
Home link on the navigation bar doesn't work

### ISSUE THREAD

**Issue by phuongtailtranminh** [terrylinooo/githuber#2]
Hi,

When I clicked on a post detail, then I want to go back to the home page, the Home link on the nav bar doesn't work

Could you please take a look at that?

Thanks

**Comment by terrylinooo** [comment]
@phuongtailtranminh 

You can upload a website icon, there will be a icon with  home link on the nav bar.
However, this theme is changed its name from Githuber to Mynote because of trademark issue, you can use Mynote theme instead.
Here is the link: https://github.com/terrylinooo/mynote
