### ISSUE TITLE
上方分類沒有出現

### ISSUE THREAD

**Issue by haway** [terrylinooo/githuber#3]
Hi

我裝了 githuber 的 WordPress 主題，但我的上方沒有出現很多顏色的分類，能請問如何除錯嗎？謝謝

網站： https://okd.guide

**Comment by terrylinooo** [comment]
@haway Hello.

這個主題在官方主題目錄審核時，因為商標問題 (GitHub) 要求我改名，所以已經改名為 Mynote。
https://github.com/terrylinooo/mynote

您可以前往下載。版本都 Mynote 主題更新。更多功能有加進 Customizer 可以自由選擇。

另外多顏色的分類必須是第一層且有文章在裡面才會出現喔。然後那個區塊是沒有放入小工具的預設值，如果有在該區塊使用小工具就會被取代。

**Comment by haway** [comment]
@terrylinooo Hi,

目前後台還是無法直接找到，應該是還在審核中？
所以我直接從 GitHub 下載後的壓縮檔名是 mynote-master.zip 
直接從管理介面上傳 zip 檔後，會顯示成功安裝。

但是在按下 外觀 -> 自訂 後，網頁會出現 500 的錯誤，錯誤的網址是：https://okd.guide/wp-admin/customize.php?theme=mynote-master&return=https%3A%2F%2Fokd.guide%2Fwp-admin%2Fthemes.php%3Ftheme%3Dmynote-master

外觀 -> 首頁，出現 500 錯誤：https://okd.guide/wp-admin/customize.php?return=%2Fwp-admin%2Fwidgets.php&autofocus%5Bcontrol%5D=header_image

我以為是 "master" 的問題，於是我用 FTP 上傳的方式在主機 /wp-content/themes 內建立 mynote 資料夾然後將解壓縮的檔案傳上去，但還是一樣。

還是我主機的問題？WordPress 5.0.3 on PHP7

附上一個 Log
[19-Feb-2019 09:02:47 UTC] PHP Warning:  require(/srv/data/web/vhosts/okd.guide/htdocs/wp-content/themes/mynote-master/classes/class-customize-alpha-color.php): failed to open stream: No such file or directory in /srv/data/web/vhosts/okd.guide/htdocs/wp-content/themes/mynote-master/functions.php on line 209

**Comment by terrylinooo** [comment]
謝謝提醒.. 要送審前修改了路徑我自己都沒發現錯誤。已修正。感謝您

**Comment by terrylinooo** [comment]
主題在送審中... 依經驗要經過一個半月才會被審到。@@

**Comment by haway** [comment]
Perfect! It works!

翻譯檔記得從 Githuber Copy 過來喔 XD

**Comment by terrylinooo** [comment]
@haway 發現您有按星星，覺得感動阿。謝謝您的支持。

Mynote 主題已經可以在官方主題庫找到了
https://wordpress.org/themes/mynote/

歡迎使用喔。
